### PR TITLE
Updates for posting

### PR DESCRIPTION
**Pull request by jaspercooper**
Hi @oscci,

I've made some updates to the post for your review. As always feel free not to implement any of these. Many of the larger ones were trying to incorporate the discussion we had with @macartan.

Once you're happy with it, you can compile the Rmd again and post the tutorial to the Discuss forum by copying and pasting the contents of the resulting `.md` (*not* `.Rmd`) file to a tutorial topic here:
http://discuss.declaredesign.org/c/tutorial

The only annoyance is you will have to manually upload the plots into the post (by clicking on the little image icon). The plots will also be generated and stored when you compile the Rmd, because I have set output to `github_document`.

Let me know if you need assistance with anything at all, and thanks so much for this awesome post. We'd love to tweet about it once it's up, if you don't mind.

Cheers,

Jasper

### CODE REVIEW

**Comment by oscci** [comment]
Aargh

Error message when I try to post.

Body is limited to 32000 characters; you entered 32281.
Sorry, new users can only put one image in a post.
Sorry, new users can only put 2 links in a post.

I already deleted the Session Info because of the length limit, but it's still too long.
Could you please fix this and upload it on my behalf.

Thanks.



On 21 Sep 2018, at 10:43, Jasper Cooper <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @oscci<https://github.com/oscci>,

I've made some updates to the post for your review. As always feel free not to implement any of these. Many of the larger ones were trying to incorporate the discussion we had with @macartan<https://github.com/macartan>.

Once you're happy with it, you can compile the Rmd again and post the tutorial to the Discuss forum by copying and pasting the contents of the resulting .md (not .Rmd) file to a tutorial topic here:
http://discuss.declaredesign.org/c/tutorial

The only annoyance is you will have to manually upload the plots into the post (by clicking on the little image icon). The plots will also be generated and stored when you compile the Rmd, because I have set output to github_document.

Let me know if you need assistance with anything at all, and thanks so much for this awesome post. We'd love to tweet about it once it's up, if you don't mind.

Cheers,

Jasper

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/oscci/deevybee_repo/pull/2

Commit Summary

  *   Change to github document
  *   Lots of minor edits and additions to text
  *   Larger change to address estimand issue
  *   Output md and other documents

File Changes

  *   M DeclareDesignIntro.Rmd<https://github.com/oscci/deevybee_repo/pull/2/files#diff-0> (159)
  *   D DeclareDesignIntro.html<https://github.com/oscci/deevybee_repo/pull/2/files#diff-1> (1535)
  *   A DeclareDesignIntro.md<https://github.com/oscci/deevybee_repo/pull/2/files#diff-2> (630)
  *   A DeclareDesignIntro_files/figure-gfm/beeswarm_plot-1.png<https://github.com/oscci/deevybee_repo/pull/2/files#diff-3> (0)
  *   A DeclareDesignIntro_files/figure-gfm/manipulation-1.png<https://github.com/oscci/deevybee_repo/pull/2/files#diff-4> (0)
  *   A DeclareDesignIntro_files/figure-gfm/plotuvars-1.png<https://github.com/oscci/deevybee_repo/pull/2/files#diff-5> (0)

Patch Links:

  *   https://github.com/oscci/deevybee_repo/pull/2.patch
  *   https://github.com/oscci/deevybee_repo/pull/2.diff

**Comment by jaspercooper** [comment]
Oh sorry about that!

Yes, will do.

**Comment by oscci** [comment]
Thanks.
To tidy things up, I've created a new repository for this, as I suspect I will be doing more with DeclareDesign.

https://github.com/oscci/simulate_designs

Thanks for your help.


On 22 Sep 2018, at 08:48, Jasper Cooper <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh sorry about that!

Yes, will do.

**Comment by jaspercooper** [comment]
Hi Dorothy, 
Here's the first draft for you to look at:
http://discuss.declaredesign.org/t/gentle-introduction-to-declaredesign-by-dorothy-bishop/51
We want to write a little intro at the top and include links to your github. Anything else you'd like to change?

**Comment by oscci** [comment]
That's all fine with me.
I'm giving a talk this week on simulating data for a reproducibility school we're running here, and I'll give DeclareDesign a shout.
My talk is at a much more basic level for total novices, but there should be some people there with more advanced skills and I think they'll be interested.

D

**Comment by jaspercooper** [comment]
Awesome, would love to hear how it goes. Thanks so much for engaging!

**Pull request merged**
